### PR TITLE
sublimetext3: fix softwareName to not conflict with sublimetext4

### PR DESCRIPTION
**Pull request by koitsu**
- For details about all of this, see https://github.com/Jackenmen/choco-auto/pull/7 which contains a long discussion about bugfixes/etc. in the ST4 package, which we needed to be able to be installed alongside ST3 without any problems.  Specifically, [this comment](https://github.com/Jackenmen/choco-auto/pull/7#issuecomment-1330204421) is relevant.
- While I'm here, fix the file type encoding on this file.  It was UTF-16 for some reason, which was confusing grep and other utils. Before:
    ```
    $ file sublimetext3/tools/*
    sublimetext3/tools/chocolateyInstall.ps1:   UTF-8 Unicode (with BOM) text
    sublimetext3/tools/chocolateyUninstall.ps1: Little-endian UTF-16 Unicode text, with CRLF line terminators
    ```
    After:
    ```
    $ file sublimetext3/tools/*
    sublimetext3/tools/chocolateyInstall.ps1:   UTF-8 Unicode (with BOM) text
    sublimetext3/tools/chocolateyUninstall.ps1: UTF-8 Unicode (with BOM) text, with CRLF line terminators
    ```

### CODE REVIEW

**Comment by koitsu** [comment]
Did not find any other files in your repo with UTF-16 encoding -- only two were `automatic/sublimetext3/tools/chocolateyUninstall.ps1` and `automatic/mysql-connector/tools/chocolateyUninstall.ps1`

**Comment by pauby** [comment]
There are a few problems with this PR. 

1. The files that have been changed, GitHub thinks are binary files. So, something is broken there.
2. Please also submit from a branch rather than your master branch.
3. Can you submit PR's for distinct things - one is to fix an issue with `sublimetext3` and the other is to fix an issue with `mysql-connector`

Thanks.

**Comment by koitsu** [comment]
1. This is not a side-effect of my change; this is a side-effect of the fact that those two files were weirdly UTF-16 LE to begin with, so GitHub cannot show you a diff (effectively it would be comparing binary to ASCII).  This is some terrible bug/quirk in GitHub; I can't fix GitHub's diff behaviour.  The files were still UTF-16 LE anyway -- `file` says so, `vim` says so, etc.. Examine them in your own branch (i.e. not this PR) with an editor which will show you encoding and you'll understand
2. OK, I will close this PR and submit a new one after renaming the branch
3. OK, I will submit a separate PR for automatic/mysql-connector/tools/chocolateyUninstall.ps1 UTF-16 LE encoding problem

**Comment by koitsu** [comment]
New PRs:

* sublimetext3: https://github.com/pauby/ChocoPackages/pull/164
* mysql-connector: https://github.com/pauby/ChocoPackages/pull/165

I explain and demonstrate the file encoding problem in the full PR description.  (And I checked your entire repository; these were the only two files that had this problem.)

**Pull request closed without merging**
