### PR TITLE
Update adobedigitaleditions_install.ahk for AHK v2 compatibility

### PR DESCRIPTION
**Pull request by jpluimers**
Fixes https://github.com/pauby/ChocoPackages/issues/187

---

Remove this line as it is incompatible with AutoHotkey version 2 and up:

``` autohotkey
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this repository (if your change does not follow the style it will likely be rejected - this includes changes in formatting / layout).
- [ ] My change requires a change to the documentation (this usually means the notes in the description of a package) and I have updated the documentation accordingly.
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] The added / modified package passed install / uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by jpluimers** [comment]
Dang: more AHK v2 compatibility issues

image

text:

``` text
513179605.ahk

Error: Function calls require a space or "(". Use comma only between parameters.
Text: SetTitleMatchMode, 1
Line: 5
File: C:\Users\jeroenp\AppData\Local\Temp\chocolatey 513179605.ahk
The script was not reloaded; the old version will remain in effect.

[Help] [Edit] [Reload] [ExitApp] [Abort]
```

Hold this pull-request for a while as it might be not possible to make it compatible with both AHK v1 and AHK v2:

https://www.autohotkey.com/boards/viewtopic.php?t=104269

> AHK version 2 has transformed commands into functions.
>
> Use AHK version 1.x.

This looks all dandy at https://www.autohotkey.com/docs/v2/v2-changes.htm

> Removed "command syntax". There are no "commands", only [function call statements](https://www.autohotkey.com/docs/v2/Language.htm#function-call-statements), which are just function or method calls without parentheses.

But in fact this is breaking as at https://www.autohotkey.com/docs/v1/Concepts.htm#functions:

> In essence, functions and commands are the same thing, so the concepts explained here apply to both. However, the long history of AutoHotkey v1 and an emphasis on backward-compatibility have resulted in a divide between commands, which require legacy syntax, and functions, which require expression syntax.

This means that the AHK v1 commands cannot be called with "expression syntax" (by using parenthesis around the parameters).

Empirically it looks like one can call single parameter functions without parenthesis, but this breaks at commands that require more than one parameter, for instance:

- https://www.autohotkey.com/docs/v1/lib/CoordMode.htm requires comma after `CoordMode`
- https://www.autohotkey.com/docs/v2/lib/CoordMode.htm forbids comma after `CoordMode`

Bummer as that will require AHK v1 to exist eternally and force their team to maintain two major versions at the same time.

**Comment by pauby** [comment]
Take a dependency on `autohotkey.portal` with a minimum version of 2.0.0 and then make the AHK script be v2 only.

**Comment by jpluimers** [comment]
That won't work: plenty of Chocolatey packages depend on AHK v1; having AHK v2 in the path will break many those AHK v1 scripts (at least the ones calling commands with 2 or more parameters cannot be made compatible).

The cause is the choice of the AHK team to make AHK v2 incompatible with AHK v1: that will make the AHK world dependent on AHK v1 forever.

**Comment by jpluimers** [comment]
Sorry I missed https://github.com/pauby/ChocoPackages/issues/187#issuecomment-1653838695 which refers to https://github.com/chocolatey-community/chocolatey-packages/pull/2246

I do have AHK v2 and AHK v1 installed at the same time through Chocolatey (AHK 2.0.4 through through [autohotkey.portable](https://community.chocolatey.org/packages/autohotkey.portable) and AHK 1.1.37.1 through [autohotkey.install](https://community.chocolatey.org/packages/autohotkey.install)).

The Chocolatey logs don't go back far enough to see which one I installed first, but I think it was "autohotkey.portable" followed by "autohotkey.install".

The situation now is that the v1 scripts fail because the 2.0.4 `authotkey.exe` is earlier in the path than the 1.1.37.1 `authotkey.exe`.

I tried figuring out through https://github.com/chocolatey-community/chocolatey-packages/pull/2246/files how it can support having had AHK v2 execute v2 scripts and AHK v1 execute v1 scripts as I think that is what you mean in that pull request.

If that is not what you mean, then how do you envision a system having a mix of v1 and v2 scripts to be selecting the correct AHK version to start them?

This is because from my experiments so far the AHK v2 introduced incompatibility around commas directly after commands will require that in order to coexist successfully with AHK v1.

**Comment by pauby** [comment]
> I tried figuring out through https://github.com/chocolatey-community/chocolatey-packages/pull/2246/files how it can support having had AHK v2 execute v2 scripts and AHK v1 execute v1 scripts as I think that is what you mean in that pull request.

To have both AHK v1 and AHK v2 installed, you need to install them in a very specific way. The docs I have in that PR points to the AHK docs on how to do it.

From memory (as that PR was a little while ago) running AHK runs v2, which figures out if your script is v1 or v2 and either executes it or hands it off to AHK v1 to execute.

**Comment by jpluimers** [comment]
> > I tried figuring out through https://github.com/chocolatey-community/chocolatey-packages/pull/2246/files how it can support having had AHK v2 execute v2 scripts and AHK v1 execute v1 scripts as I think that is what you mean in that pull request.
> 
> To have both AHK v1 and AHK v2 installed, you need to install them in a very specific way. The docs I have in that PR points to the AHK docs on how to do it.
> 
> From memory (as that PR was a little while ago) running AHK runs v2, which figures out if your script is v1 or v2 and either executes it or hands it off to AHK v1 to execute.

After a long search, I found the documentation at https://www.autohotkey.com/docs/v2/Program.htm#install

Those steps are convoluted at best, and I won't have time (the sales of our house went way faster than anticipated, so I need the limited energy for all kinds of things surrounding the move to the new home) until at least the end of november.

Hopefully by then I still find back this pull request and can execute the steps in the documentation and then start to understand how AutoHotkey v2 is selected by v2 scripts and AutoHotkey v1 by v1 scripts (I could not understand that from the AutoHotkey documentation).

**Comment by pauby** [comment]
I've gone ahead and merged this. Removing that won't havce much if any effect on what the scripts do.

Thanks @jpluimers for taking hte trouble to put this in. I believe when `autohotkey.install` v2 is released it would have fixed this. But that has been in review for some time.

**Pull request merged**
