### PR TITLE
(adobereader) Migrated package and updated to latest version

### PR DESCRIPTION
**Pull request by pauby**
## Description
Migrated the package from https://github.com/open-circle-ltd/chocolatey.adobe-acrobat-reader-dc to here and updated it.

## Motivation and Context
The package was outdated and broken. [This PR](https://github.com/open-circle-ltd/chocolatey.adobe-acrobat-reader-dc/pull/37) fixed the package, but it was unfortunately not merged. See comments [here](https://github.com/open-circle-ltd/chocolatey.adobe-acrobat-reader-dc/pull/37#issuecomment-1607511636), [here](https://github.com/open-circle-ltd/chocolatey.adobe-acrobat-reader-dc/pull/37#issuecomment-1609300438), and [here](https://github.com/open-circle-ltd/chocolatey.adobe-acrobat-reader-dc/pull/37#issuecomment-1612828310).

## How Has this Been Tested?
Installed in Chocolatey Test Environment with Chocolatey CLI version 1.4.0 and 2.1.0.

## Screenshot (if appropriate, usually isn't needed):

This confirms the package installs successfully (on Windows Server 2019):

image

This confirms the correct version of the software is installed.

image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this repository (if your change does not follow the style it will likely be rejected - this includes changes in formatting / layout).
- [x] My change requires a change to the documentation (this usually means the notes in the description of a package) and I have updated the documentation accordingly.
- [x] I have updated the package description and it is less than 4000 characters.
- [x] The added / modified package passed install / uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by aledeniz** [comment]
Just to confirm: I have tested this PR internally for the last two releases, and it has worked fine in hundreds of computers.
That said, we tend to keep all our estate at the latest version or close by, so this limits the version distribution of our target computers.

**Comment by pauby** [comment]
Thanks @aledeniz. I will do a few more tests of this and if they all work as they should, I'll push it to the repository this weekend.

**Comment by pauby** [comment]
This works on a fresh install.

Screenshot_20230701_164532

I've tested this by installing version `2023.001.20093` first. Then I installed the version from this PR and it fails to install with a 1618 error.

Screenshot_20230701_162859

The log file it refers to contains:

```text
=== Verbose logging started: 01/07/2023  16:26:46  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\System32\msiexec.exe ===
MSI (c) (84:7C) [16:26:46:232]: Resetting cached policy values
MSI (c) (84:7C) [16:26:46:232]: Machine policy value 'Debug' is 0
MSI (c) (84:7C) [16:26:46:232]: ******* RunEngine:
           ******* Product: {AC76BA86-1033-FF00-7760-BC15014EA700}
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (84:7C) [16:26:46:232]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (84:7C) [16:26:49:232]: Failed to grab execution mutex. System error 258.
MSI (c) (84:7C) [16:26:49:232]: Cloaking enabled.
MSI (c) (84:7C) [16:26:49:232]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (84:7C) [16:26:49:232]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (c) (84:7C) [16:26:49:232]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (84:7C) [16:26:49:232]: MainEngineThread is returning 1618
=== Verbose logging stopped: 01/07/2023  16:26:49 ===

MSI (s) (14:00) [16:26:56:044]: User policy value 'DisableRollback' is 0
MSI (s) (14:00) [16:26:56:044]: Machine policy value 'DisableRollback' is 0
MSI (s) (14:00) [16:26:56:044]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (14:00) [16:26:56:044]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (14:00) [16:26:56:044]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (14:00) [16:26:56:044]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (14:00) [16:26:56:044]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (14:00) [16:26:56:044]: Destroying RemoteAPI object.
MSI (s) (14:F4) [16:26:56:044]: Custom Action Manager thread ending.
```

Which I don't think helps much.

If I install `2023.001.20093` and then try to upgrade to a later version that doesn't have this PR (`2023.001.20143`), it works:

Screenshot_20230701_163431

So, I think there is something in this PR, or it could be the patch, that is breaking the upgrades from earlier versions. I'm going to try to upgrade from another earlier version just in case.

**Comment by pauby** [comment]
Installing `2023.001.20293.1` and then upgrading to the version for this PR, works.

image

**Comment by pauby** [comment]
Upgrading from `2023.1.20143` works:

image

**Pull request merged**
