### PR TITLE
add oracle certificate to trust its drivers

### LINKED ISSUE #41: Virtualbox Guest Additions package uses AutoHotekey to click on driver install button without checks
When installing  the package [virtualbox-guest-additions-guest.install](https://chocolatey.org/packages/virtualbox-guest-additions-guest.install) there are no checks by the AHK script as to what drivers are being installed. See if we can check for this.

### PR DESCRIPTION
**Pull request by tardyp**
This has been verified on windows server 2019 and works in headless mode.

fixes #41

### CODE REVIEW

**Comment by pauby** [comment]
Thanks for doing that PR. When we chatted via email I assumed you were extracting the cert from the ISO some way. In order to distribute the cert in the package we need redistribution rights for the Chocolatey Community Repository. I have npt gone through the fine print of the license but I am fairly sure that's not the case?

**Comment by tardyp** [comment]
Indeed, I did not realize that public certificate is copyrightable material. Extracting it from iso will not be trivial. It is probably buried inside the kernel drivers, which are themselves inside the .exe installer :(

**Comment by pauby** [comment]
_Anything_ that is distributed with the package that belong to somebody else (in this case Oracle) needs to be allowed. The certificate doesn't belong to Chocolatey. It belongs to Oracle so requires rights to distribute it. See https://chocolatey.org/docs/legal#distributions

**Comment by tardyp** [comment]
You can actually find the cert in VBox opensource edition:

https://www.virtualbox.org/svn/vbox/trunk/src/VBox/HostDrivers/Support/Certificates/Trusted-OracleCorporationVirtualBox-05308b76ac2e15b29720fb4395f65f38.cer

So it is distributed under the GPL License
https://www.virtualbox.org/wiki/Contributor_information

**Comment by tardyp** [comment]
do you want me to download that file from the svn server?

**Comment by pauby** [comment]
Can it be done programatically at runtime?

**Comment by tardyp** [comment]
I don't think the SVN server is a proper CDN download. I think it is more reasonable and reliable to distribute this file in the nupkg as it is GPL and we have the rights to do so.
I modified the patch to include license of the file

**Comment by pauby** [comment]
We also need a VERIFICATION.txt file with the correct checksums for the GPL certificate version matching the bundled one.

**Comment by tardyp** [comment]
added VERIFICATION.txt

**Comment by tardyp** [comment]
Hi @pauby I think I did everything requested on this PR. I am not sure why it is staled.

**Comment by pauby** [comment]
@tardyp It's my fault. Apologies. I've started a review and didn't finish it some time ago! There was just once change needed and I think we're good to go!

**Comment by tardyp** [comment]
done..

**Comment by pauby** [comment]
@tardyp Awesome work! Thanks for your contribution!

**Comment by BryceBeagle** [comment]
It looks like you removed all usages of autohotkey from the install script, but autohotkey is still listed as a dependency. Is this intentional?

**Comment by pauby** [comment]
Thanks @BryceBeagle for reporting that! Fixed in PR #46

**Pull request merged**
